#+TITLE: linux tips
#+SUBTITLE: quick reference for common things i need to do
#+AUTHOR: xdrie
#+DATE: 2020-04-09
#+TAGS[]: ref
#+TOC: true

a wip collection of notes and tips on random things i end up needing to do with my system.
i expand it as i encounter new tasks, and hopefully i can consult it instead of looking things up next time.

* ssh
** config file
put the config file in ~~/.ssh/config~.
now, hosts can be referenced simply by a short name, and all port and user configuration can be managed from this file.
*** example
#+begin_src 
Host host-name
  Hostname x.x.x.x
  User user
  IdentityFile ~/.ssh/id_rsa
#+end_src
*** variations
ssh tunnels with config: https://starkandwayne.com/blog/setting-up-an-ssh-tunnel-with-ssh-config/
** ed25519 key
much of this information taken from [[https://blog.g3rt.nl/upgrade-your-ssh-keys.html][upgrade your ssh keys]]

*** why?
in summary,
> DSA and RSA 1024 bit are deprecated now
> Increase resistance to brute-force password cracking

*** generating the new key
#+begin_src sh
ssh-keygen -o -a 100 -t ed25519
#+end_src

this will generate the key to ~~/.ssh/id_ed25519~

everything else is pretty much the exact same!

** restrict to command
in authorized keys, the [[https://www.virtono.com/community/tutorial-how-to/restrict-executable-ssh-commands-with-authorized-keys/][command]] option can be used to restrict the user to a single command
* desktop
** kde
compositor:
+ Compositor can be toggled with Shift+Alt+F12 by default
kwin:
+ KWin can be restarted with `kwin --replace &`, sometimes it's `kwin_x11` instead
+ sometimes fonts in titlebars break, no fix is known other than resetting X
+ compositor can be sped up in ~Display Settings > Compositor~
** xdg
*** default browser
setting default browser using ~xdg~ commands (also applies to generally setting [[https://wiki.archlinux.org/index.php/default_applications#xdg-open][default applications]])

to set the default browser to Firefox:
#+begin_src sh
xdg-settings set default-web-browser firefox.desktop
#+end_src

to get the current default browser
#+begin_src sh
# get the default web browser
xdg-settings get default-web-browser
#+end_src

* laptop
** battery
*** powertop
wip write this section
*** cpu scaling
using the auto-cpufreq tool
https://ol.reddit.com/r/linux/comments/ejxx9f/github_autocpufreq_automatic_cpu_speed_power/
https://github.com/AdnanHodzic/auto-cpufreq
(blog post) https://foolcontrol.org/?p=3124
https://ol.reddit.com/r/linux/comments/ejxx9f/github_autocpufreq_automatic_cpu_speed_power/fd4y36k/
* dev
** vim
*** run command and append input
~:r !command~
example:
#+begin_export ascii
   September 2019         October 2019          November 2019   
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa
 1  2  3  4  5  6  7         1  2  3  4  5                  1  2
 8  9 10 11 12 13 14   6  7  8  9 10 11 12   3  4  5  6  7  8  9
15 16 17 18 19 20 21  13 14 15 16 17 18 19  10 11 12 13 14 15 16
22 23 24 25 26 27 28  20 21 22 23 24 25 26  17 18 19 20 21 22 23
29 30                 27 28 29 30 31        24 25 26 27 28 29 30
                                                                
#+end_export
** emacs
see [[brain:emacs][emacs]]
*** org-mode
see [[brain:org%20mode][org-mode]]
** git
*** gitignore whitelisting
information on [[https://jasonstitt.com/gitignore-whitelisting-patterns][gitignore whitelisting patterns]].
*** global gitignore
towrite
* wine
*** 32-bit wineprefix
+ Use wine like this: ~WINEPREFIX="$HOME/.wine32" WINEARCH=win32 wine~
* tinc
DigitalOcean [[https://www.digitalocean.com/community/tutorials/how-to-install-tinc-and-set-up-a-basic-vpn-on-ubuntu-18-04%0A][tutorial]] on basic TINC configuration
* productivity
** calendar
Calendar can be synchronized and accessed through the [[https://lostpackets.de/khal/index.html][Khal]] terminal calendar program | [[https://lostpackets.de/khal/configure.html][configuration instructions]] 
Khal requires [[https://vdirsyncer.pimutils.org/en/stable/tutorial.html][vdirsyncer]] to be set up to read from CalDAV calendars.
Google Calendar provides a [[https://developers.google.com/calendar/caldav/v2/guide][CalDAV API]] that needs to be enabled to access calendars through this protocol to allow syncing.

** email
TOWRTE
* unix
** users
*** add user to group
on arch:
#+begin_src sh
sudo gpasswd -a xdrie docker
#+end_src

on ubuntu:
#+begin_src sh
sudo usermod -aG docker xdrie
#+end_src
** cron
*** edit crontab
edit crontab for a particular user. to edit the system wide crontab, use ~sudo~.
#+begin_src sh
crontab -e
#+end_src

*** fields
this [[https://stackoverflow.com/a/35575322/13240621][stackoverflow post]] explains the format of crontab entries.
* tools
** filesystem watching
use [[https://github.com/clibs/entr][entr]] to run arbitrary commands when a file changes:
#+begin_src sh
ag -g hw | entr org2pdf hw9.org ~/Downloads/hw9_sub.pdf   
#+end_src
this will watch the ~hw~ directory and run the command whenever it is updated.
in this case it's a live preview for a PDF generated from an Org document.
* misc
** pull all git repositories
unix command to pull all repositories:
#+begin_src sh
for d in ./*/ ; do (cd "$d" && git pull --all); done
#+end_src

