#+TITLE: alticu matrix
#+SUBTITLE: the ALTiCU matrix network
#+AUTHOR: xdrie
#+DATE: 2020-06-06
#+TAGS[]: alticu
#+TOC: true

* intro
As of today (2020-06-06), our new communication network https://matrix.alt.icu/ is online.
ALTiCU Matrix is powered by the federated [[https://matrix.org/][Matrix]] network, and currently serves the [[https://about.riot.im/][Riot]] web client.

* what is matrix?
Being a federated network, Matrix works similarly to email: though our users have accounts on our own instance, they are able to communicate with users across the global network of instances, just as an email from one domain can still send mail to other domains.
This creates a decentralized network with no single point of failure, and removes the problem of a central authority being able to manage all communications.

Matrix also provides [[https://matrix.org/docs/guides/end-to-end-encryption-implementation-guide][state of the art end to end encryption]], ensuring that only the intended recepients are able to decrypt and view messages, providing privacy and security by default. Users are fully in control of their own data.

To connect to Matrix and use it for communication, one of [[https://matrix.org/clients/][many clients]] can be used (start with our web frontend). There are many clients to choose from for every desktop platform, and for the major mobile platforms.

To learn more about matrix, see this excellent [[https://hacks.mozilla.org/2018/10/dweb-decentralised-real-time-interoperable-communication-with-matrix/][blog post]].

* recommended clients
+ desktop: [[https://riot.im/download/desktop/][riot desktop]] (if you don't mind dealing with buggy beta software [[https://github.com/Nheko-Reborn/nheko/releases][nheko]])
+ web: [[matrix.alt.icu/][hosted riot]]
+ android: [[https://matrix.org/docs/projects/client/riotx][riotX]]
+ ios: [[https://matrix.org/docs/projects/client/riot-ios][riot]]

* summary
matrix instance is available at https://matrix.alt.icu
